name: CI
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore Packages
      run: nuget restore 'MWR FoV Changer.sln'
    
    - name: Build solution
      run: msbuild 'MWR FoV Changer.sln' -t:rebuild -property:Configuration=Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build
        path: bin/Release
            
